### PR TITLE
Fix f2fs not booting

### PR DESCRIPTION
**Pull request by DerRomtester**
- tested and it is working
- the mount option noatime needs to be removed in the fstab

### CODE REVIEW

**Comment by erorcun** [comment]
Why noatime needs to be removed?

**Comment by DerRomtester** [comment]
I dont know. I just checked the logs. And this value is unrecognized: 
Only needs to be removed from the f2fs mount option ext4 is fine of course
<3>[    4.867545] F2FS-fs (mmcblk0p28): Unrecognized mount option "noatime" or missing value
<3>[    4.867620] F2FS-fs (mmcblk0p28): Unrecognized mount option "noatime" or missing value
<7>[    5.010722] SELinux: initialized (dev mmcblk0p28, type f2fs), uses xattr
<3>[    5.053375] F2FS-fs (mmcblk0p28): Unrecognized mount option "noatime" or missing value
<3>[    5.053449] F2FS-fs (mmcblk0p28): Unrecognized mount option "noatime" or missing value
<7>[    5.186059] SELinux: initialized (dev mmcblk0p28, type f2fs), uses xattr
<3>[    5.210251] F2FS-fs (mmcblk0p16): Unrecognized mount option "noatime" or missing value
<3>[    5.210324] F2FS-fs (mmcblk0p16): Unrecognized mount option "noatime" or missing value
<7>[    5.215378] SELinux: initialized (dev mmcblk0p16, type f2fs), uses xattr
<7>[    5.223723] SELinux: initialized (dev mmcblk0p1, type vfat), uses genfs_contexts
<3>[    5.229054] EXT4-fs (mmcblk0p14): Unrecognized mount option "noatime" or missing value

**Comment by erorcun** [comment]
Ugh, there is no exact solution on internet it seems, so i'm picking it as is, thanks again.

**Comment by DerRomtester** [comment]
This commit shouldnt be there sry
https://github.com/erorcun/android_kernel_oneplus_msm8974-3.10/pull/1/commits/baf8988f69fa2f76256b634415b3aaa7693e7c38

**Comment by erorcun** [comment]
Np

**Pull request merged**
